# Generated by Django 5.1.4 on 2025-02-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
