# Generated by Django 5.1.7 on 2025-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kbank", "ธนาคารกสิกรไทย"),
                    ("scb", "ธนาคารไทยพาณิชย์"),
                    ("bbl", "ธนาคารกรุงเทพ"),
                    ("ktb", "ธนาคารกรุงไทย"),
                    ("bay", "ธนาคารกรุงศรีอยุธยา"),
                    ("ttb", "ธนาคารทหารไทยธนชาต"),
                    ("gsb", "ธนาคารออมสิน"),
                    ("baac", "ธ.ก.ส."),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
