# Generated by Django 5.1.4 on 2025-02-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refund_requests",
                to="myapp.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="account_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
