# Generated by Django 5.1.4 on 2025-02-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_member_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
