# Generated by Django 5.1.4 on 2025-02-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("member", "Member"),
                    ("seller", "Seller"),
                    ("admin", "Admin"),
                ],
                default="guest",
                max_length=10,
            ),
        ),
    ]
