# Generated by Django 5.1.4 on 2025-02-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_refundrequest_item_alter_refundrequest_account_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("refunded", "Refunded"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
