# Generated by Django 5.1.7 on 2025-03-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='last_withdrawn_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
