# Generated by Django 5.1.4 on 2025-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_refundrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="confirmed_by_user",
            field=models.BooleanField(default=False),
        ),
    ]
