# Generated by Django 5.1.4 on 2025-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_review_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_sold",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
