# Generated by Django 5.1.7 on 2025-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sellerwallet_last_withdrawn_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('kbank', 'ธนาคารกสิกรไทย'), ('scb', 'ธนาคารไทยพาณิชย์'), ('bbl', 'ธนาคารกรุงเทพ'), ('ktb', 'ธนาคารกรุงไทย'), ('bay', 'ธนาคารกรุงศรีอยุธยา'), ('ttb', 'ธนาคารทหารไทยธนชาต'), ('gsb', 'ธนาคารออมสิน'), ('baac', 'ธ.ก.ส.'), ('other', 'ธนาคารอื่นๆ')], max_length=50, null=True),
        ),
    ]
