# Generated by Django 5.1.4 on 2025-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_refundrequest_confirmed_by_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="refund_proof",
            field=models.ImageField(blank=True, null=True, upload_to="refund_proofs/"),
        ),
    ]
