# Generated by Django 5.1.4 on 2025-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_order_city_order_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
