# Generated by Django 5.1.5 on 2025-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_is_reported_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_community_post',
            field=models.BooleanField(default=False),
        ),
    ]
