# Generated by Django 5.1.4 on 2025-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_customuser_managers_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="email",
            field=models.EmailField(
                default="default@example.com", max_length=254, unique=True
            ),
        ),
    ]
