# Generated by Django 5.1.4 on 2025-01-26 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_groupcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_group_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grouppost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
