# Generated by Django 5.1.4 on 2025-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_refundrequest_refund_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proof/"),
        ),
    ]
