# Generated by Django 5.1.5 on 2025-02-16 06:30

import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_post_is_community_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐ 1'), (2, '⭐ 2'), (3, '⭐ 3'), (4, '⭐ 4'), (5, '⭐ 5')]),
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=myapp.models.review_media_upload_path)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='myapp.review')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
