# Generated by Django 5.1.4 on 2025-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_order_city_alter_order_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอดำเนินการ"),
                    ("shipped", "จัดส่งแล้ว"),
                    ("delivered", "จัดส่งสำเร็จ"),
                    ("cancelled", "ยกเลิกแล้ว"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
