# Generated by Django 5.1.4 on 2025-02-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_seller_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
