# Generated by Django 5.1.7 on 2025-03-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_seller_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='last_withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
