# Generated by Django 5.1.7 on 2025-03-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sellerwallet_last_withdrawn_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerwallet',
            name='last_withdrawn_at',
        ),
    ]
