# Generated by Django 5.1.5 on 2025-02-16 19:43

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_review_created_at_alter_review_rating_reviewmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=myapp.models.upload_to)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='myapp.grouppost')),
            ],
            options={
                'verbose_name_plural': 'Group Post Media',
                'ordering': ['created_at'],
            },
        ),
    ]
