# Generated by Django 5.1.4 on 2025-02-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอดำเนินการ"),
                    ("shipped", "จัดส่งแล้ว"),
                    ("delivered", "จัดส่งสำเร็จ"),
                    ("refunded", "ขอคืนเงิน"),
                    ("cancelled", "ยกเลิกแล้ว"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
