# Generated by Django 5.1.4 on 2025-02-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_seller_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
