# Generated by Django 5.1.7 on 2025-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_sellerwallet_last_withdrawn_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='last_withdrawal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
