# Generated by Django 5.1.5 on 2025-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_grouppostmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostmedia',
            name='file',
            field=models.FileField(upload_to='group_posts/'),
        ),
    ]
