# Generated by Django 5.1.4 on 2025-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="return_item_proof",
            field=models.ImageField(
                blank=True, null=True, upload_to="return_item_proofs/"
            ),
        ),
    ]
