# Generated by Django 5.1.4 on 2025-02-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="confirmed_by_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="payment_proof",
            field=models.ImageField(
                blank=True, null=True, upload_to="withdraw_proofs/"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอดำเนินการ"),
                    ("approved", "อนุมัติแล้ว"),
                    ("rejected", "ถูกปฏิเสธ"),
                    ("paid", "โอนเงินแล้ว"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
