# Generated by Django 5.1.4 on 2025-03-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_sellernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="analysis_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                default="neutral",
                max_length=10,
            ),
        ),
    ]
