# Generated by Django 5.1.4 on 2025-02-02 12:12

import myapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_remove_post_image_remove_post_video_postmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Posts"},
        ),
        migrations.AlterModelOptions(
            name="postmedia",
            options={"ordering": ["created_at"], "verbose_name_plural": "Post Media"},
        ),
        migrations.AddField(
            model_name="postmedia",
            name="caption",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="file",
            field=models.FileField(upload_to=myapp.models.upload_to),
        ),
    ]
