# Generated by Django 5.1.4 on 2025-03-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_review_analysis_done_review_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
