# Generated by Django 5.1.4 on 2025-02-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_post_options_alter_postmedia_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="shared_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_by",
                to="myapp.post",
            ),
        ),
    ]
