# Generated by Django 5.1.4 on 2025-03-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_product_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="summary",
        ),
        migrations.AddField(
            model_name="review",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
