# Generated by Django 5.1.4 on 2025-02-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_post", "New Post"),
                    ("new_comment", "New Comment"),
                    ("like_post", "Post Liked"),
                    ("share_post", "Post Shared"),
                    ("new_follower", "New Follower"),
                    ("refund_request", "Refund Request"),
                    ("like_group_post", "Group Post Liked"),
                    ("comment_group_post", "Group Post Commented"),
                    ("new_order", "New Order"),
                    ("new_review", "New Review"),
                    ("refund_request", "Refund Request"),
                    ("refund_completed", "Refund Completed"),
                    ("order_shipped", "Order Shipped"),
                    ("refund_approved", "Refund Approved"),
                    ("refund_rejected", "Refund Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
