# Generated by Django 5.1.5 on 2025-02-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_post_is_community_post'),
        ('notifications', '0002_notification_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.grouppost'),
        ),
    ]
