# Generated by Django 5.1.5 on 2025-02-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_grouppost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_post', 'New Post'), ('new_comment', 'New Comment'), ('like_post', 'Post Liked'), ('share_post', 'Post Shared'), ('new_follower', 'New Follower'), ('new_order', 'New Order'), ('new_review', 'New Review'), ('refund_request', 'Refund Request'), ('like_group_post', 'Group Post Liked'), ('comment_group_post', 'Group Post Commented')], max_length=20),
        ),
    ]
